server:
  port: 9090

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/shop_db
    username: root
    password: sang123
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none        # mình tự tạo bảng bằng SQL, không để Hibernate tự tạo
    properties:
      hibernate:
        format_sql: true
